# docker-compose.yml
version: '3.8'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/learn-tensorflow  # This mounts the current directory to /app in the container
